### ISSUE TITLE
Lobby Upgrade

### ISSUE THREAD

**Issue by sergiosalesa** [UNIZAR-30226-2024-02/Front-end-movil#27]
Mejorar el Lobby y crear la seleccion de skins

**Comment by 737275** [comment]
He implementado una pantalla de lobby como la que existe en el front web, la que vosotros llamabais lobby no era exactamente un lobby de partida sino la lista de partidas disponibles, esta pantalla ahora se llama "Partidas".

He adaptado también casi todas las funcionalidades de web. Dado el importante acoplamiento entre el manejo de la partida y la lógica de la partida propiamente para obtener los valores reales válidos, aconsejo que trabajemos sobre la rama "lobby-partida", y borra la rama de la lógica de la partida, la cual he mergeado a la nueva creada.
